version: '3'
services:
  learningbase:
    image: goendalf666/learningbase_aicps:latest
    container_name: learningbase_test
    volumes:
      - ai_system:/tmp
    command: ["echo", "This is the learningbase container. Mounted /tmp from ai_system."]

  activationbase:
    image: goendalf666/activationbase_aicps:latest
    container_name: activationbase_test
    volumes:
      - ai_system:/tmp
    command: ["echo", "This is the activationbase container. Mounted /tmp from ai_system."]

volumes:
  ai_system:
