# docker-compose.ols.yml
version: "3.0"

volumes:
  ai_system:
    external: true

services:
  knowledgebase_ols:
    image: goendalf666/knowledgebase_aicps:latest
    container_name: knowledgebase_ols
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - -c
      - |
        # Remove old stuff, copy OLS model from the container to /tmp/OLS/knowledgeBase
        rm -rf /tmp/OLS/knowledgeBase
        mkdir -p /tmp/OLS/knowledgeBase
        cp -r /app/knowledgeBase/* /tmp/OLS/knowledgeBase/
        tail -f /dev/null

  activationbase_ols:
    image: goendalf666/activationbase_aicps:latest
    container_name: activationbase_ols
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - -c
      - |
        rm -rf /tmp/OLS/activationBase
        mkdir -p /tmp/OLS/activationBase
        cp -r /app/activationBase/* /tmp/OLS/activationBase/
        tail -f /dev/null

  codebase_ols:
    image: goendalf666/codebase_aicps:latest
    container_name: codebase_ols
    depends_on:
      - knowledgebase_ols
      - activationbase_ols
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - -c
      - |
        rm -rf /tmp/OLS/codeBase
        mkdir -p /tmp/OLS/codeBase
        cp -r /app/codeBase/* /tmp/OLS/codeBase/
        # Possibly run an OLS script if you have Python installed
        # python3 /tmp/OLS/codeBase/apply_olsSolution.py ...
        tail -f /dev/null
